function outputFiles = exportMealPlan(selectedCandidate, menuPool, data, config, runInfo, projectRoot)
% Result export

outputFolder = fullfile(projectRoot, char(config.OutputFolder));
if ~exist(outputFolder, 'dir')
    mkdir(outputFolder);
end

% Timestamped output
timeStamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
excelFile = fullfile(outputFolder, ['MealPlan_' timeStamp '.xlsx']);
textFile = fullfile(outputFolder, ['MealPlan_' timeStamp '.txt']);

recipes = data.Recipes;
D = data.NumberOfDays;
M = data.NumberOfMeals;

% 21-row menu
menuRows = cell(D * M, 14);
rowIndex = 0;
for dayIndex = 1:D
    for mealIndex = 1:M
        rowIndex = rowIndex + 1;
        selectedRecipe = find(selectedCandidate.Z(:, dayIndex, mealIndex) > 0.5, 1);
        menuRows(rowIndex, :) = { ...
            data.DayNames(dayIndex), ...
            data.MealNames(mealIndex), ...
            recipes.RecipeID(selectedRecipe), ...
            recipes.RecipeName(selectedRecipe), ...
            recipes.Cuisine(selectedRecipe), ...
            recipes.Calories_kcal(selectedRecipe), ...
            recipes.Protein_g(selectedRecipe), ...
            recipes.Carbs_g(selectedRecipe), ...
            recipes.Fat_g(selectedRecipe), ...
            recipes.Sugar_g(selectedRecipe), ...
            recipes.Fiber_g(selectedRecipe), ...
            recipes.Sodium_mg(selectedRecipe), ...
            recipes.PrepTime_min(selectedRecipe), ...
            data.ApproximateRecipeCost(selectedRecipe)};
    end
end

menuTable = cell2table(menuRows, 'VariableNames', { ...
    'Day', 'Meal', 'RecipeID', 'Recipe', 'Cuisine', 'Calories_kcal', ...
    'Protein_g', 'Carbs_g', 'Fat_g', 'Sugar_g', 'Fiber_g', ...
    'Sodium_mg', 'PrepTime_min', 'ApproxIngredientCost_CAD'});
% String columns
menuTable.Day = string(menuTable.Day);
menuTable.Meal = string(menuTable.Meal);
menuTable.RecipeID = string(menuTable.RecipeID);
menuTable.Recipe = string(menuTable.Recipe);
menuTable.Cuisine = string(menuTable.Cuisine);


% Purchased ingredients
purchasedIndex = find(selectedCandidate.Packages > 0);
shoppingTable = table( ...
    data.Ingredients.IngredientID(purchasedIndex), ...
    data.Ingredients.IngredientName(purchasedIndex), ...
    data.Ingredients.PackageSize_g(purchasedIndex), ...
    data.CurrentPrice(purchasedIndex), ...
    selectedCandidate.Packages(purchasedIndex), ...
    data.Ingredients.PackageSize_g(purchasedIndex) .* selectedCandidate.Packages(purchasedIndex), ...
    selectedCandidate.IngredientUse_g(purchasedIndex), ...
    selectedCandidate.Waste_g(purchasedIndex), ...
    data.CurrentPrice(purchasedIndex) .* selectedCandidate.Packages(purchasedIndex), ...
    'VariableNames', {'IngredientID', 'Ingredient', 'PackageSize_g', ...
    'PricePerPackage_CAD', 'PackagesToBuy', 'PurchasedWeight_g', ...
    'UsedWeight_g', 'LeftoverWeight_g', 'TotalCost_CAD'});

% Daily nutrition
dailyNutritionTable = table( ...
    data.DayNames', ...
    selectedCandidate.DailyNutrients(1, :)', ...
    selectedCandidate.DailyNutrients(2, :)', ...
    selectedCandidate.DailyNutrients(3, :)', ...
    selectedCandidate.DailyNutrients(4, :)', ...
    selectedCandidate.DailyNutrients(5, :)', ...
    selectedCandidate.DailyNutrients(6, :)', ...
    selectedCandidate.DailyNutrients(7, :)', ...
    selectedCandidate.DailyPreparationTime', ...
    'VariableNames', {'Day', 'Calories_kcal', 'Protein_g', 'Carbs_g', ...
    'Fat_g', 'Sugar_g', 'Fiber_g', 'Sodium_mg', 'PreparationTime_min'});

% Run summary
summaryTable = table( ...
    ["Selected price month"; "Weekly budget (CAD)"; "Estimated grocery cost (CAD)"; ...
    "Chinese lunches/dinners"; "Number of candidate menus"; ...
    "Selected candidate"; "Unique recipes"; "Average preference"; ...
    "Total leftover weight (g)"; "Best quality value"], ...
    [string(config.SelectedMonth); string(config.WeeklyBudget_CAD); ...
    string(selectedCandidate.TotalCost); string(selectedCandidate.ChineseLunchDinnerCount); ...
    string(runInfo.NumberOfCandidates); string(runInfo.SelectedIndex); ...
    string(selectedCandidate.UniqueRecipes); string(selectedCandidate.AveragePreference); ...
    string(selectedCandidate.TotalWaste_g); string(runInfo.BestQuality)], ...
    'VariableNames', {'Metric', 'Value'});

% Candidate comparison
numberOfCandidates = numel(menuPool);
candidateID = (1:numberOfCandidates)';
qualityValue = zeros(numberOfCandidates, 1);
totalCost = zeros(numberOfCandidates, 1);
totalWaste = zeros(numberOfCandidates, 1);
averagePreference = zeros(numberOfCandidates, 1);
uniqueRecipes = zeros(numberOfCandidates, 1);
chineseCount = zeros(numberOfCandidates, 1);

for candidateIndex = 1:numberOfCandidates
    qualityValue(candidateIndex) = menuPool(candidateIndex).QualityValue;
    totalCost(candidateIndex) = menuPool(candidateIndex).TotalCost;
    totalWaste(candidateIndex) = menuPool(candidateIndex).TotalWaste_g;
    averagePreference(candidateIndex) = menuPool(candidateIndex).AveragePreference;
    uniqueRecipes(candidateIndex) = menuPool(candidateIndex).UniqueRecipes;
    chineseCount(candidateIndex) = menuPool(candidateIndex).ChineseLunchDinnerCount;
end

candidateTable = table(candidateID, qualityValue, totalCost, totalWaste, ...
    averagePreference, uniqueRecipes, chineseCount, ...
    'VariableNames', {'Candidate', 'QualityValue', 'TotalCost_CAD', ...
    'TotalLeftover_g', 'AveragePreference', 'UniqueRecipes', ...
    'ChineseLunchDinnerCount'});

% Excel output
writetable(menuTable, excelFile, 'Sheet', 'WeeklyMenu');
writetable(shoppingTable, excelFile, 'Sheet', 'ShoppingList');
writetable(dailyNutritionTable, excelFile, 'Sheet', 'DailyNutrition');
writetable(summaryTable, excelFile, 'Sheet', 'Summary');
writetable(candidateTable, excelFile, 'Sheet', 'CandidateComparison');

% Text output
fileID = fopen(textFile, 'w');
if fileID < 0
    error('Unable to create text output: %s', textFile);
end
cleanupObject = onCleanup(@() fclose(fileID));

fprintf(fileID, 'WEEKLY MEAL PLAN\n');
fprintf(fileID, 'Price month: %s\n', char(config.SelectedMonth));
fprintf(fileID, 'Estimated cost: CAD %.2f\n', selectedCandidate.TotalCost);
fprintf(fileID, 'Chinese lunches/dinners: %d of 14\n\n', selectedCandidate.ChineseLunchDinnerCount);

for dayIndex = 1:D
    fprintf(fileID, '%s\n', char(data.DayNames(dayIndex)));
    dayRows = menuTable.Day == data.DayNames(dayIndex);
    currentDay = menuTable(dayRows, :);
    for mealIndex = 1:height(currentDay)
        fprintf(fileID, '  %-10s %s (%s)\n', char(currentDay.Meal(mealIndex)), ...
            char(currentDay.Recipe(mealIndex)), char(currentDay.Cuisine(mealIndex)));
    end
    fprintf(fileID, '\n');
end

fprintf(fileID, 'SHOPPING LIST\n');
for ingredientIndex = 1:height(shoppingTable)
    fprintf(fileID, '  %-24s %d package(s), CAD %.2f, leftover %.0f g\n', ...
        char(shoppingTable.Ingredient(ingredientIndex)), ...
        shoppingTable.PackagesToBuy(ingredientIndex), ...
        shoppingTable.TotalCost_CAD(ingredientIndex), ...
        shoppingTable.LeftoverWeight_g(ingredientIndex));
end

% Save plots
plotFiles = plotMealPlan(menuTable, shoppingTable, dailyNutritionTable, ...
    candidateTable, selectedCandidate, data, outputFolder, timeStamp);

outputFiles.ExcelFile = excelFile;
outputFiles.TextFile = textFile;
outputFiles.PlotFiles = plotFiles;
end
